### ISSUE TITLE
error while loading shared libraries: libreadline.so.6

### ISSUE THREAD

**Issue by Lillianwu0314** [mpmeers/SEACR#80]
Hi all,

I've installed SEACR with bioconda and was trying to run it, but received the following error:

error while loading shared libraries: libreadline.so.6: cannot open shared object file: No such file or directory

I tried to update SEACR with conda update seacr, but it tells me All requested packages already installed. 

What should I do to get libreadline.so.6 in my conda environment?

Thanks,
Lillian

**Comment by mpmeers** [comment]
Hi Lillian,

I'm not aware of libreadline or how it relates to SEACR, but it sounds like this might be a versioning issue where your Conda environment updated to a libreadline might be incompatible with another package (e.g. R, [like in this thread](https://github.com/bioconda/bioconda-recipes/issues/13439)). Perhaps you can try verifying your Conda dependencies and reinstalling older versions where necessary? Going to close this since it isn't directly related to a SEACR issue.

Mike
