### ISSUE TITLE
Inconsistent naming convention causing failed peak calling

### ISSUE THREAD

**Issue by loganminhdang** [mpmeers/SEACR#85]
I have been having trouble performing peak calling with the SEACR webserver. The error message produced by the server is as follows: 

***** WARNING: File - has inconsistent naming convention for record:
JH584304.1 4516 114452 7.09631e+06 698.594 JH584304.1:103897-103899
***** WARNING: File - has inconsistent naming convention for record:
JH584304.1 4516 114452 7.09631e+06 698.594 JH584304.1:103897-103899

From the error message, I'm speculating that my bedgraph file has a naming convention that is different from what SEACR prefers. This is how my bedgraph files look(for both IgG control and target bedgraph files): 
...
chr1	34124234	34124256	1
chr1	34124391	34124463	1
chr1	34125170	34125287	2
chr1	34125287	34125341	3
chr1	34125341	34125410	4
....

This is the genome file I used for bedtool conversion from bed to bedgraph files: 
...
chr14	124902244
chr15	104043685
chr16	98207768
chr17	94987271
chr18	90702639
chr19	61431566
chrX	171031299
chrY	91744698
chrM	16299
GL456210.1	169725
GL456211.1	241735
GL456212.1	153618
GL456213.1	39340
.....

Any clues to how to solve this problem will be much appreciated. Thank you!

**Comment by mpmeers** [comment]
Hi,

Apologies for the delay in getting to this. I believe this is a bedtools issue (e.g. [this thread](https://github.com/arq5x/bedtools2/issues/628))--since SEACR does a bedtools intersect to filter out control regions, if the experimental and control bedgraphs have different naming conventions it will throw this error. In this case, "JH584304.1 4516" is not consistent with the "chr1, chr2 ... chrN" naming convention, so that chr name needs to be adjusted or else those regions need to be omitted.

Mike
